// <auto-generated />
using BlueBits.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlueBits.Api.Migrations
{
    [DbContext(typeof(BlueBitsDbContext))]
    [Migration("20260613002217_FixPendingModelChanges")]
    partial class FixPendingModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("BlueBits.Api.Models.File", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FileId");

                    b.HasIndex("SessionId");

                    b.ToTable("Files", t =>
                        {
                            t.HasCheckConstraint("CHK_FileType", "\"FileType\" IN ('Image', 'Docx', 'Other')");
                        });
                });

            modelBuilder.Entity("BlueBits.Api.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaterialId");

                    b.ToTable("Materials", t =>
                        {
                            t.HasCheckConstraint("CHK_MaterialYear", "\"MaterialYear\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("BlueBits.Api.Models.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NoteId");

                    b.HasIndex("FileId");

                    b.HasIndex("SessionId");

                    b.ToTable("Notes", t =>
                        {
                            t.HasCheckConstraint("CHK_NoteType", "\"NoteType\" IN ('GeneralNote', 'FileNote')");
                        });
                });

            modelBuilder.Entity("BlueBits.Api.Models.Prompt", b =>
                {
                    b.Property<int>("PromptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromptName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PromptId");

                    b.HasIndex("SystemCode")
                        .IsUnique();

                    b.HasIndex("WorkflowId");

                    b.ToTable("Prompts");

                    b.HasData(
                        new
                        {
                            PromptId = 1,
                            PromptName = "Lecture Extraction",
                            PromptText = "You are an AI extracting lectures...",
                            SystemCode = "PROMPT_LEC_EXT",
                            WorkflowId = 1
                        },
                        new
                        {
                            PromptId = 2,
                            PromptName = "Bank Extraction",
                            PromptText = "You are an AI extracting banks...",
                            SystemCode = "PROMPT_BANK_EXT",
                            WorkflowId = 2
                        },
                        new
                        {
                            PromptId = 3,
                            PromptName = "Lecture Coordination",
                            PromptText = "Coordinate this lecture...",
                            SystemCode = "PROMPT_LEC_COORD",
                            WorkflowId = 3
                        },
                        new
                        {
                            PromptId = 4,
                            PromptName = "Bank Coordination",
                            PromptText = "Coordinate this bank...",
                            SystemCode = "PROMPT_BANK_COORD",
                            WorkflowId = 4
                        },
                        new
                        {
                            PromptId = 5,
                            PromptName = "Draw Using AI",
                            PromptText = "Generate markdown/mermaid drawings...",
                            SystemCode = "PROMPT_DRAW_AI",
                            WorkflowId = 7
                        },
                        new
                        {
                            PromptId = 6,
                            PromptName = "Bank Questions",
                            PromptText = "Generate quiz questions for the bank...",
                            SystemCode = "PROMPT_BANK_QS",
                            WorkflowId = 6
                        });
                });

            modelBuilder.Entity("BlueBits.Api.Models.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LectureNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LectureType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("Sessions", t =>
                        {
                            t.HasTrigger("TRG_PruneSessionData");

                            t.HasCheckConstraint("CHK_LectureNumber", "\"LectureNumber\" > 0");

                            t.HasCheckConstraint("CHK_LectureType", "\"LectureType\" IN ('Theoretical', 'Practical')");
                        });
                });

            modelBuilder.Entity("BlueBits.Api.Models.SessionContent", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContentId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionContents");
                });

            modelBuilder.Entity("BlueBits.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatchNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamJoinDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("TelegramUsername", "UserRole")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CHK_BatchNumber", "\"BatchNumber\" > 0");

                            t.HasCheckConstraint("CHK_UserRole", "\"UserRole\" IN ('Admin', 'TechMember', 'ScientificMember')");
                        });

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BatchNumber = 1,
                            CreatedAt = "2026-01-01T00:00:00.0000000Z",
                            FirstName = "Mostafa",
                            LastName = "Shraief",
                            Password = "Admin@123",
                            UserRole = "Admin",
                            Username = "MostafaShraief"
                        },
                        new
                        {
                            UserId = 2,
                            BatchNumber = 1,
                            CreatedAt = "2026-01-01T00:00:00.0000000Z",
                            FirstName = "John",
                            LastName = "Tech",
                            Password = "Tech@2026",
                            UserRole = "TechMember",
                            Username = "john_tech"
                        },
                        new
                        {
                            UserId = 3,
                            BatchNumber = 1,
                            CreatedAt = "2026-01-01T00:00:00.0000000Z",
                            FirstName = "Sara",
                            LastName = "Siri",
                            Password = "something",
                            UserRole = "ScientificMember",
                            Username = "SaraSiri"
                        });
                });

            modelBuilder.Entity("BlueBits.Api.Models.Workflow", b =>
                {
                    b.Property<int>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSessionsPerUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowId");

                    b.HasIndex("SystemCode")
                        .IsUnique();

                    b.ToTable("Workflows");

                    b.HasData(
                        new
                        {
                            WorkflowId = 1,
                            AdminNote = "Lecture Extraction Workflow",
                            IsActive = 1,
                            MaxSessionsPerUser = 5,
                            SystemCode = "LEC_EXT"
                        },
                        new
                        {
                            WorkflowId = 2,
                            AdminNote = "Bank Extraction Workflow",
                            IsActive = 1,
                            MaxSessionsPerUser = 5,
                            SystemCode = "BANK_EXT"
                        },
                        new
                        {
                            WorkflowId = 3,
                            AdminNote = "Lecture Coordination Workflow",
                            IsActive = 1,
                            MaxSessionsPerUser = 5,
                            SystemCode = "LEC_COORD"
                        },
                        new
                        {
                            WorkflowId = 4,
                            AdminNote = "Bank Coordination Workflow",
                            IsActive = 1,
                            MaxSessionsPerUser = 5,
                            SystemCode = "BANK_COORD"
                        },
                        new
                        {
                            WorkflowId = 6,
                            AdminNote = "Bank Questions Workflow",
                            IsActive = 1,
                            MaxSessionsPerUser = 10,
                            SystemCode = "BANK_QS"
                        },
                        new
                        {
                            WorkflowId = 7,
                            AdminNote = "Draw AI Workflow (Beta)",
                            IsActive = 1,
                            MaxSessionsPerUser = 5,
                            SystemCode = "DRAW"
                        },
                        new
                        {
                            WorkflowId = 8,
                            AdminNote = "Merge Workflow (Beta)",
                            IsActive = 1,
                            MaxSessionsPerUser = 5,
                            SystemCode = "MERGE"
                        },
                        new
                        {
                            WorkflowId = 9,
                            AdminNote = "Pandoc Full Document with Template",
                            IsActive = 1,
                            MaxSessionsPerUser = 5,
                            SystemCode = "PANDOC_FULL"
                        },
                        new
                        {
                            WorkflowId = 10,
                            AdminNote = "Pandoc Single Blank Page",
                            IsActive = 1,
                            MaxSessionsPerUser = 5,
                            SystemCode = "PANDOC_BLANK"
                        });
                });

            modelBuilder.Entity("BlueBits.Api.Models.WorkflowPermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PermissionId");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("RoleName", "WorkflowId")
                        .IsUnique();

                    b.ToTable("WorkflowPermissions", t =>
                        {
                            t.HasCheckConstraint("CHK_RoleName", "\"RoleName\" IN ('TechMember', 'ScientificMember')");
                        });

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            RoleName = "TechMember",
                            WorkflowId = 1
                        },
                        new
                        {
                            PermissionId = 2,
                            RoleName = "TechMember",
                            WorkflowId = 2
                        },
                        new
                        {
                            PermissionId = 3,
                            RoleName = "TechMember",
                            WorkflowId = 3
                        },
                        new
                        {
                            PermissionId = 4,
                            RoleName = "TechMember",
                            WorkflowId = 4
                        },
                        new
                        {
                            PermissionId = 7,
                            RoleName = "TechMember",
                            WorkflowId = 7
                        },
                        new
                        {
                            PermissionId = 8,
                            RoleName = "TechMember",
                            WorkflowId = 8
                        },
                        new
                        {
                            PermissionId = 10,
                            RoleName = "ScientificMember",
                            WorkflowId = 6
                        },
                        new
                        {
                            PermissionId = 11,
                            RoleName = "TechMember",
                            WorkflowId = 9
                        },
                        new
                        {
                            PermissionId = 12,
                            RoleName = "TechMember",
                            WorkflowId = 10
                        });
                });

            modelBuilder.Entity("BlueBits.Api.Models.File", b =>
                {
                    b.HasOne("BlueBits.Api.Models.Session", "Session")
                        .WithMany("Files")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BlueBits.Api.Models.Note", b =>
                {
                    b.HasOne("BlueBits.Api.Models.File", "File")
                        .WithMany("Notes")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlueBits.Api.Models.Session", "Session")
                        .WithMany("Notes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BlueBits.Api.Models.Prompt", b =>
                {
                    b.HasOne("BlueBits.Api.Models.Workflow", "Workflow")
                        .WithMany("Prompts")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("BlueBits.Api.Models.Session", b =>
                {
                    b.HasOne("BlueBits.Api.Models.Material", "Material")
                        .WithMany("Sessions")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlueBits.Api.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlueBits.Api.Models.Workflow", "Workflow")
                        .WithMany("Sessions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("User");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("BlueBits.Api.Models.SessionContent", b =>
                {
                    b.HasOne("BlueBits.Api.Models.Session", "Session")
                        .WithMany("SessionContents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BlueBits.Api.Models.WorkflowPermission", b =>
                {
                    b.HasOne("BlueBits.Api.Models.Workflow", "Workflow")
                        .WithMany("Permissions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("BlueBits.Api.Models.File", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("BlueBits.Api.Models.Material", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("BlueBits.Api.Models.Session", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Notes");

                    b.Navigation("SessionContents");
                });

            modelBuilder.Entity("BlueBits.Api.Models.User", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("BlueBits.Api.Models.Workflow", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Prompts");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
